# Generated by Django 3.1.7 on 2021-04-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210405_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketProduct',
        ),
    ]
