# Generated by Django 3.1.7 on 2021-04-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
