# Generated by Django 3.1.7 on 2021-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='delevery', max_length=255),
            preserve_default=False,
        ),
    ]
